name: sync-repo-settings

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

jobs:
  sync-repo-settings:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: "tudortimi"
      
      - name: Update Repository Settings
        uses: joshjohanning/bulk-github-repo-settings-sync-action@v1
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          dry-run: ${{ github.event_name == 'pull_request' }}
          owner: "tudortimi"
          repositories: "all"
          delete-branch-on-merge: true
          allow-squash-merge: false
